export interface Service {
  icon: string;
  title: string;
  des: string;
  values: string[];
  ourWorks: string[];
  route: string;
}

const servicesList: Service[] = [
  {
    icon: "/assets/services/services-sec/outer.svg",
    title: "التصاميم الخارجية",
    des: "التصميم الخارجي هو عملية تصميم الجزء الظاهر الخارجي من المبنى، مثل السقف والواجهات وأي عناصر مرئية خارجية أخرى، فهو يعكس شخصية مالكه وينقل رسالة محددة من خلال إنشاء تصميم مميز وفريد. يحدد التصميم الخارجي مدى انسجام المبنى من الداخل والخارج ومع الجوار المحيط، بالإضافة إلى تأثيره إيجابًا على وظائف المبنى، من خلال التخطيط الجيد للتصميم الخارجي وإنشاء مساحات خارجية عمليّة وجميلة",
    values: [
      "تخطيط مواقع الإنشاء",
      "توثيق الأعمال كما نُفِّذت",
      "نمذجة التضاريس الرقمية (DTM)",
      "المسح باستخدام GPS وتقنية الليزر سكــــــــــــان",
      "عداد المخططات على برامج الـCAD",
      " الرفع المساحي الطبوغرافي",
    ],
    ourWorks: [
      "/real-projects/38.jpg",
      "/real-projects/36.jpg",
      "/favorite/1.jpg",
      "/favorite/2.jpg",
      "/real-projects/1.jpg",
      "/real-projects/2.jpg",
      "/favorite/29.jpg",
      "/favorite/36.jpg",
      "/real-projects/10.jpg",
      "/real-projects/12.jpg",
      "/real-projects/4.jpg",
      "/real-projects/9.jpg",
    ],
    route: "/services/exterior-designs",
  },
  {
    icon: "/assets/services/services-sec/internal.svg",
    title: "التصاميم الداخليه",
    des: "تكمن أهمية التصميم الداخلي في استغلال المساحات بأفضل شكل ممكن بما يحقق الراحة والجمال والعملية في آن واحد. فنحن نعمل على فهم طبيعة المكان ووظيفته، ثم نعيد توزيع العناصر الداخلية بطريقة مدروسة تضمن الانسيابية وسهولة الحركة وتوفير الإضاءة المثالية. يعتمد فريقنا على اختيار المواد والألوان والأنماط التي تعكس هوية المكان وتعزز من راحة المستخدمين",
    values: [
      "تخطيط مواقع الإنشاء",
      "توثيق الأعمال كما نُفِّذت",
      "نمذجة التضاريس الرقمية (DTM)",
      "المسح باستخدام GPS وتقنية الليزر سكــــــــــــان",
      "عداد المخططات على برامج الـCAD",
      " الرفع المساحي الطبوغرافي",
    ],
    ourWorks: [
      "/real-projects/38.jpg",
      "/real-projects/36.jpg",
      "/favorite/1.jpg",
      "/favorite/2.jpg",
      "/real-projects/1.jpg",
      "/real-projects/2.jpg",
      "/favorite/29.jpg",
      "/favorite/36.jpg",
      "/real-projects/10.jpg",
      "/real-projects/12.jpg",
      "/real-projects/4.jpg",
      "/real-projects/9.jpg",
    ],
    route: "/services/interior-designs",
  },
  {
    icon: "/assets/services/services-sec/garden.svg",
    title: "لاندسكيب وتنسيق حدائق",
    des: "للنباتات دور حيوي في الحديقة فهي مصدر الخضرة، وتساهم في تنقية الجو من الملوثات وتلطيفه وتخفيف الضوضاء، كما أنها توفر الظل وتضبط حرارة الجو وتزيد نسبة الرطوبة، وأيضا فإن مزيج خضرة النباتات مع ألوان الزهور يمنح أثرا نفسيا رائعا، يبعث على السرور والسعادة والراحة النفسية والهدوء، ويخفف عن المواطنين مشكلاتهم الحياتية وهمومهم مما يساعدهم على تجديد النشاط والحيوية، وزيادة القدرة على العطاء والإنتاج. نظرا لذلك اولينا اهتماماً خاص بخدمه تنسيق الحدائق تحت إشراف هندسي إحترافي ومتميز",
    values: [
      "تخطيط مواقع الإنشاء",
      "توثيق الأعمال كما نُفِّذت",
      "نمذجة التضاريس الرقمية (DTM)",
      "المسح باستخدام GPS وتقنية الليزر سكــــــــــــان",
      "عداد المخططات على برامج الـCAD",
      " الرفع المساحي الطبوغرافي",
    ],
    ourWorks: [
      "/real-projects/38.jpg",
      "/real-projects/36.jpg",
      "/favorite/1.jpg",
      "/favorite/2.jpg",
      "/real-projects/1.jpg",
      "/real-projects/2.jpg",
      "/favorite/29.jpg",
      "/favorite/36.jpg",
      "/real-projects/10.jpg",
      "/real-projects/12.jpg",
      "/real-projects/4.jpg",
      "/real-projects/9.jpg",
    ],
    route: "/services/landscape",
  },
  {
    icon: "/assets/services/services-sec/area.svg",
    title: "خدمات هندسه المساحه",
    des: "الرفع المساحي ينتج عندما يتم الإعداد لعمل القرار المساحي وهو بمثابة الخريطة التي يتم طباعتها على الأرض، ومن شأنها أن توضح كافة جهات وقياسات الأرض سواء الأبعاد أو المساحة الكلية والارتفاع، عند الشروع في بناء أي عقار أيا كان الغرض منه، لتحديد الزوايا المشتركة مع البناء من مباني وأراضٍ مجاورة، ونقدم لك في مكتبنا إعداد التقرير المساحي لتقديم للجهة المختصة خاليا من العيوب ومناسب لكود البناء المصري بنسبة 100%",
    values: [
      "تخطيط مواقع الإنشاء",
      "توثيق الأعمال كما نُفِّذت",
      "نمذجة التضاريس الرقمية (DTM)",
      "المسح باستخدام GPS وتقنية الليزر سكــــــــــــان",
      "عداد المخططات على برامج الـCAD",
      " الرفع المساحي الطبوغرافي",
    ],
    ourWorks: [
      "/real-projects/38.jpg",
      "/real-projects/36.jpg",
      "/favorite/1.jpg",
      "/favorite/2.jpg",
      "/real-projects/1.jpg",
      "/real-projects/2.jpg",
      "/favorite/29.jpg",
      "/favorite/36.jpg",
      "/real-projects/10.jpg",
      "/real-projects/12.jpg",
      "/real-projects/4.jpg",
      "/real-projects/9.jpg",
    ],
    route: "/services/surveying-engineering",
  },
  {
    icon: "/assets/services/services-sec/work.svg",
    title: "أعمال الترميم",
    des: "تتأثر العديد من البنايات بالعوامل الزمنية، حيث تبدأ بعض الشروخ والتصدعات في الظهور مما قد يعرض المبنى للانهيار، وهذا من شأنه الإضرار بسلامة السكان والمباني المجاورة؛ هنا يأتي دورنا الهندسي لمعرفة طرق الإصلاحات اللازم تنفيذها لضمان سلامة المبنى والمحافظة عليه وعلي ساكنيه.",
    values: [
      "تخطيط مواقع الإنشاء",
      "توثيق الأعمال كما نُفِّذت",
      "نمذجة التضاريس الرقمية (DTM)",
      "المسح باستخدام GPS وتقنية الليزر سكــــــــــــان",
      "عداد المخططات على برامج الـCAD",
      " الرفع المساحي الطبوغرافي",
    ],
    ourWorks: [
      "/real-projects/38.jpg",
      "/real-projects/36.jpg",
      "/favorite/1.jpg",
      "/favorite/2.jpg",
      "/real-projects/1.jpg",
      "/real-projects/2.jpg",
      "/favorite/29.jpg",
      "/favorite/36.jpg",
      "/real-projects/10.jpg",
      "/real-projects/12.jpg",
      "/real-projects/4.jpg",
      "/real-projects/9.jpg",
    ],
    route: "/services/restoration-works",
  },
  {
    icon: "/assets/services/services-sec/build.svg",
    title: "الاعمال الإنشائية",
    des: "تشمل الأعمال الإنشائية جميع المراحل الأساسية لبناء المنشآت من البداية وحتى التسليم، بدءًا من أعمال الحفر والأساسات مرورًا بالهياكل الخرسانية والمعدنية، ووصولًا إلى تنفيذ الجدران والأسقف وفق أعلى معايير الجودة. نحرص في أعمالنا الإنشائية على تطبيق كود البناء المصري والالتزام بأدق المواصفات الهندسية لضمان متانة المبنى وسلامته على المدى الطويل، مع الاهتمام بكل التفاصيل لتحقيق أفضل نتائج عملية وجمالية.",
    values: [
      "تخطيط مواقع الإنشاء",
      "توثيق الأعمال كما نُفِّذت",
      "نمذجة التضاريس الرقمية (DTM)",
      "المسح باستخدام GPS وتقنية الليزر سكــــــــــــان",
      "عداد المخططات على برامج الـCAD",
      " الرفع المساحي الطبوغرافي",
    ],
    ourWorks: [
      "/real-projects/38.jpg",
      "/real-projects/36.jpg",
      "/favorite/1.jpg",
      "/favorite/2.jpg",
      "/real-projects/1.jpg",
      "/real-projects/2.jpg",
      "/favorite/29.jpg",
      "/favorite/36.jpg",
      "/real-projects/10.jpg",
      "/real-projects/12.jpg",
      "/real-projects/4.jpg",
      "/real-projects/9.jpg",
    ],
    route: "/services/construction-works",
  },
];

export default servicesList;
